services:
  pgvector-db:
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    container_name: pgvector-db
    environment:
      POSTGRES_USER: sgadmin
      POSTGRES_PASSWORD: sg4dm1n!
      POSTGRES_DB: db_rag
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/db_rag_backup.sql:/docker-entrypoint-initdb.d/db_rag_backup.sql

volumes:
  pgdata:
